spring:
  application:
    name: preis-service
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}

server:
  port: 0

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true